version: "3.4"
services:
  cdc-postgres:
    image: postgres:16-alpine
    container_name: cdc-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeducoin
      POSTGRES_PORT: 5432
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "cafeducoin"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  cdc-koa:
    container_name: cdc-koa-container
    build:
      context: ./cafeducoin-koa
      dockerfile: ./Dockerfile
      target: base
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cafeducoin
      DB_HOST: cdc-postgres
      DB_PORT: 5432
      JWT_SECRET_KEY: cafeducoinjwtsecretkey
    depends_on:
      cdc-postgres:
        condition: service_healthy
    ports:
      - "7654:7654"
      - "9229:9229"
    volumes:
      - ./cafeducoin-koa/src:/cafeducoin/src
      - ./cafeducoin-koa/nodemon.json:/cafeducoin/nodemon.json
    command: npm run debug

  cdc-vue:
    restart: unless-stopped
    container_name: cdc-vue-container
    build:
      context: ./cafeducoin-vue
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 8000:8000
    environment:
      - VITE_API_HOSTNAME=cdc-koa  
    depends_on:
      - cdc-koa
    volumes:
      - ./cafeducoin-vue/src:/cafeducoin-vue/src
    command: npm run dev -- --host="0.0.0.0"
        
volumes:
  postgres-data:
