version: "3.4"
services:
  cdc-postgres:
    image: postgres:16-alpine
    container_name: cdc-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeducoin
      POSTGRES_PORT: 5432
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "cafeducoin"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  cdc-koa:
    container_name: cdc-koa-container
    build:
      context: ./cafeducoin-koa
      dockerfile: ./Dockerfile
      target: production
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cafeducoin
      DB_HOST: cdc-postgres
      DB_PORT: 5432
      JWT_SECRET_KEY: cafeducoinjwtsecretkey
    depends_on:
      cdc-postgres:
        condition: service_healthy
    ports:
      - 7654:7654
    command: node dist/server.js

  cdc-vue:
    container_name: cdc-vue-container
    restart: unless-stopped
    build:
      context: ./cafeducoin-vue
      dockerfile: ./Dockerfile
    environment:
      - VITE_API_HOSTNAME=cdc-koa
    ports:
      - 8080:80
    depends_on:
      - cdc-koa
        
volumes:
  postgres-data:
